spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/okBoard?serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/YOUR_OUTPUT_DIR/
  mvc:
    view:
      prefix: /static/
      suffix: .html
server:
  port: 8080
  max-http-header-size: 65536